Project_06_Minerals/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^minerals_app/', include('minerals_app.urls', namespace='minerals_app')),
    url(r'^$', views.index), # was '^$'
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()


minerals_app/urls.py
from django.conf.urls import url

from . import views


app_name="minerals_app"  # needed for the include() function


urlpatterns = [
    url(r'minerals_app/(?P<pk>\d+)/$', views.mineral_detail, name='detail'),
    url(r'', views.mineral_list, name='list'),
]


minerals_app/models.py
from django.db import models


class Minerals(models.Model):
    name = models.CharField(max_length=255)
    image_filename = models.CharField(max_length=255, null=True, blank=True, default=None)
    image_caption = models.CharField(max_length=255, null=True, blank=True, default=None)
    category = models.CharField(max_length=255, null=True, blank=True, default=None)
    formula = models.CharField(max_length=255, null=True, blank=True, default=None)
    strunz_classification = models.CharField(max_length=255, null=True, blank=True, default=None)
    crystal_system = models.CharField(max_length=255, null=True, blank=True, default=None)
    unit_cell = models.CharField(max_length=255, null=True, blank=True, default=None)
    color = models.CharField(max_length=255, null=True, blank=True, default=None)
    crystal_symmetry = models.CharField(max_length=255, null=True, blank=True, default=None)
    cleavage = models.CharField(max_length=255, null=True, blank=True, default=None)
    mohs_scale_hardness = models.CharField(max_length=255, null=True, blank=True, default=None)
    luster = models.CharField(max_length=255, null=True, blank=True, default=None)
    streak = models.CharField(max_length=255, null=True, blank=True, default=None)
    diaphaneity = models.CharField(max_length=255, null=True, blank=True, default=None)
    optical_properties = models.CharField(max_length=255, null=True, blank=True, default=None)
    group = models.CharField(max_length=255, null=True, blank=True, default=None)
    refractive_index = models.CharField(max_length=255, null=True, blank=True, default=None)
    crystal_habit = models.CharField(max_length=255, null=True, blank=True, default=None)
    specific_gravity = models.CharField(max_length=255, null=True, blank=True, default=None)

    def __str__(self):
        return self.name

Project_06_Minerals/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'minerals_app/index.html')

minerals_app/views.py
from django.shortcuts import get_object_or_404, render
from django.db.models import Count, Q
from django.contrib.auth.models import User
import random
from .models import Minerals


def mineral_list(request):
    """list view, all of the minerals_app"""
    minerals = Minerals.objects.all()
    random_key = random.randint(1, len(minerals))
    return render(request, 'minerals_app/mineral_list.html',
                  {'minerals': minerals,
                   'randomKey': random_key})


def mineral_detail(request, pk):
    """detail view of a mineral"""
    mineral = get_object_or_404(Minerals, pk=pk)
    return render(request, 'minerals_app/mineral_detail.html',
                  {'mineral': mineral})


minerals_app/templates/minerals_app/index.html
{% extends 'layout.html' %}

{% block content %}
    <a href="{% url 'minerals_app:list' %}">Click here to see the list of minerals.</a>
{% endblock %}

minerals_app/templates/minerals_app/mineral_detail.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% load mineral_extras %}

{% block content %}
    <div class="grid-100 mineral__container">
    <h1 class="mineral__name">{{ mineral.name|title }}</h1>
    <div class="mineral__image-bg">
        <img class="mineral__image" src="{% static 'images/' %}{{ mineral.name }}.jpg">
        <p class="mineral__caption">{{ mineral.image_caption }}</p>
    </div>
    <div class="mineral__table-container">
        <table class="mineral__table">
            <tr>
                <td class="mineral__category">Category</td>
                <td>{{ mineral.category|title }}</td>
            </tr>
            <tr>
            <td class="mineral__category">Formula</td>
            <td class="mineral__formula">{{ mineral.formula|safe|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Strunz Classification</td>
            <td>{{ mineral.strunz_classification|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Unit Cell</td>
            <td>{{ mineral.unit_cell|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Color</td>
            <td>{{ mineral.color|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Crystal Habit</td>
            <td>{{ mineral.crystal_habit|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Mohs Scale Hardness</td>
            <td>{{ mineral.mohs_scale_hardness|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Luster</td>
            <td>{{ mineral.luster|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Streak</td>
            <td>{{ mineral.streak|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Diaphaneity</td>
            <td>{{ mineral.diaphaneity|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Optical properties</td>
            <td>{{ mineral.optical_properties|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Group</td>
            <td>{{ mineral.group|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Refractive index</td>
            <td>{{ mineral.refractive_index|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Crystal habit</td>
            <td>{{ mineral.crystal_habit|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Specific gravity</td>
            <td>{{ mineral.specific_gravity|title }}</td>
          </tr>
        </table>
    </div>
    </div>
{% endblock %}

minerals_app/templates/minerals_app/mineral_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="bounds">
    <ul class="minerals__container">
        {% for mineral in minerals %}
            <li class="minerals__item">
                <a class="minerals__anchor" href="{% url 'minerals_app:detail' pk=mineral.pk %}">{{ mineral.name }}</a>
            </li>
        {% endfor %}
    </ul>
    </div>

    <div class="minerals__random">
        <a class="minerals__anchor" href="{% url 'minerals_app:detail' pk=randomKey %}">Show random mineral</a>
    </div>

{% endblock %}

templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Luk's Minerals: Look at these minerals</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
</head>
<body>
<div class="bounds">
<div class="grid-100">
  <a href="{% url 'minerals_app:list' %}">
    <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
      <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
      <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
      <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
    </svg>
    <h1 class="logo__name text-centered">Luk's Minerals</h1>
  </a>
  <p class="logo__text text-centered">Rock on, with Rocks!</p>

    {% block content %}{% endblock %}
</div>
</div>
</body>
</html>